location                      = "uksouth"
virtual_network_name          = "new-ado-vnet"
virtual_network_rg            = "ado-vnet"
subnet_name                   = "vmSubnet"
managed_identity_name         = "gitops-vm-identity"
keyvault_name                 = "gitops_vm_kv"
ssh_key_name                  = "adminuser-ssh-private-key"
vmSku                         = "Standard_D2_v4"
