--- 
- name: Manage svc.sh script
  hosts: localhost
  become: true
  tasks:
    - name: Check if svc.sh is installed
      shell: ./svc.sh status
      args:
        chdir: /home/adminuser/azp
      register: svc_status
      ignore_errors: yes

    - name: Install the service if not installed
      shell: ./svc.sh install
      args:
        chdir: /home/adminuser/azp
      when: "'not installed' in svc_status.stdout"

    - name: Start the service if not running
      shell: ./svc.sh start
      args:
        chdir: /home/adminuser/azp
      when: "'not installed' in svc_status.stdout or 'not running' in svc_status.stdout or 'stopped' in svc_status.stdout"
  
    # - name: Validate Packages
    #   shell: |
    #     ls -al
    #     chmod +x ./check.sh
    #     ./check.sh
    #   register: additional_script_result

    - name: Display the contents of /var/log/provisioner.log
      shell: cat /var/log/provisioner.log
      register: validation_log
      ignore_errors: yes

    - name: Show validation log
      debug:
        msg: "{{ validation_log.stdout }}"

# - name: Run svc.sh script
#   hosts: localhost
#   tasks:
#     - name: Install and start the service
#       become: true
#       shell: cd /home/adminuser/azp && ./svc.sh install && ./svc.sh start
